arb-dir: lib/l10n
template-arb-file: app_pl.arb
output-localization-file: localizations.dart
output-class: AppLocalizations
preferred-supported-locales: [pl]
untranslated-messages-file: untranslated.json