name: radioaktywne
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: '>=3.7.9 <4.0.0'

dependencies:
  async: ^2.10.0
  collection: ^1.17.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_comms: ^0.0.6+2
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.5
  freezed_annotation: ^2.2.0
  go_router: ^6.5.0
  intl: ^0.17.0
  json_annotation: ^4.8.0
  leancode_hooks: ^0.0.3+1
  logging: ^1.1.1
  oktoast: ^3.3.1
  provider: ^6.0.5
  rxdart: ^0.27.7
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.2.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  go_router_builder: ^1.1.0
  json_serializable: ^6.6.1
  leancode_lint: ^2.1.0
  mockito: ^5.3.2

flutter_gen:
  output: lib/resources/

  integrations:
    flutter_svg: true
    lottie: true

flutter:
  uses-material-design: true
  assets:
    - assets/