name: radioaktywne
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.7.9 <4.0.0'

dependencies:
  async: ^2.10.0
  audio_service: ^0.18.13
  audio_video_progress_bar: ^2.0.3
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_comms: ^1.1.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10
  # Core version of the library for parsing 
  # and displaying widgets from raw HTML.
  # If any features (e.g. embeds) are missing,
  # replace with `flutter_widget_from_html`.
  flutter_widget_from_html_core: ^0.15.2
  freezed_annotation: ^2.2.0
  go_router: ^14.2.7
  html_unescape: ^2.0.0
  http: ^1.2.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  just_audio: ^0.9.40
  # TODO: add later if needed (e.g. to fix #31)
  # just_audio_background: ^0.0.1-beta.13
  leancode_hooks: ^0.0.6
  logging: ^1.1.1
  oktoast: ^3.4.0
  provider: ^6.1.2
  rxdart: ^0.27.7
  simple_animations: ^5.0.2
  simple_shadow: ^0.3.1
  text_scroll: ^0.2.0
  uuid: ^4.5.0

dev_dependencies:
  build_runner: ^2.4.11
  flutter_gen_runner: ^5.7.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  go_router_builder: ^2.4.1
  json_serializable: ^6.8.0
  leancode_lint: ^13.0.0
  mockito: ^5.3.2

flutter_gen:
  output: lib/resources/

  integrations:
    flutter_svg: true
    lottie: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: "assets/ra_logo/RA_logo_transparent.png"
  image_path_ios: "assets/ra_logo/RA_logo_dark.png"
  adaptive_icon_background: "#302318"
  adaptive_icon_foreground: "assets/ra_logo/RA_logo_transparent_108px.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/ra_logo/
  fonts:
    - family: RadikalWUT
      fonts:
        - asset: assets/fonts/radikalwut-bold.otf
    - family: Arial
      fonts:
        - asset: assets/fonts/arial.ttf