name: radioaktywne
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.7.9 <4.0.0'

dependencies:
  async: ^2.10.0
  audio_service: ^0.18.12
  collection: ^1.17.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_comms: ^0.0.6+2
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.5
  freezed_annotation: ^2.2.0
  go_router: ^6.5.0
  http: ^1.1.0
  intl: ^0.18.0
  json_annotation: ^4.8.0
  just_audio: ^0.9.34
  leancode_hooks: ^0.0.3+1
  logging: ^1.1.1
  marquee: ^2.2.3
  oktoast: ^3.3.1
  provider: ^6.0.5
  rxdart: ^0.27.7
  simple_animations: ^5.0.2
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.2.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  go_router_builder: ^1.1.0
  json_serializable: ^6.6.1
  leancode_lint: ^2.1.0
  mockito: ^5.3.2

flutter_gen:
  output: lib/resources/

  integrations:
    flutter_svg: true
    lottie: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: "assets/ra_logo/RA_logo_transparent.png"
  image_path_ios: "assets/ra_logo/RA_logo_dark.png"
  adaptive_icon_background: "#302318"
  adaptive_icon_foreground: "assets/ra_logo/RA_logo_transparent_108px.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/ra_logo/
  fonts:
    - family: RadikalWUT
      fonts:
        - asset: assets/fonts/radikalwut-bold.otf
    - family: Arial
      fonts:
        - asset: assets/fonts/arial.ttf